FROM nginx
COPY index.html /usr/share/nginx/html
COPY index.css /usr/share/nginx/html
COPY index.js /usr/share/nginx/html
COPY login/ /usr/share/nginx/html/login
COPY myevents/ /usr/share/nginx/html/myevents
COPY signup/ /usr/share/nginx/html/signup
ADD default.conf /etc/nginx/conf.d/default.conf
